apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Reference the deployment manifest
resources:
  - deployment.yaml
# Dynamically set the Docker image name and tag
images:
  - name: IMAGE_PLACEHOLDER # Matches placeholder in deployment.yaml
    newName: "016246143337.dkr.ecr.eu-west-3.amazonaws.com/lab-chrisley75-ecr-6if" # Can be changed dynamically
    newTag: "build-17" # Can be updated via CI/CD
